### ISSUE TITLE
Skin changed but still can't register

### ISSUE THREAD

**Issue by K0-RR** [unmojang/drasl#100]
Hi, my Mojang username is `_K0RR_`.
After changing the skin I waited for 5 minutes and drasl still can't validate it.
[`https://pl.namemc.com/profile/_K0RR_`](https://pl.namemc.com/profile/_K0RR_)

**Comment by evan-goode** [comment]
I can't reproduce the error on a fresh Drasl 2.0.0 instance or on https://drasl.unmojang.org. Could you maybe try again, and then try again with a different browser if that didn't work? You will need to start from the [registration page](https://drasl.unmojang.org/web/registration) and enter your username.

Make sure you use the most recent skin PNG it gives you rather than any older one. The verification skins are different depending on your username and a cookie in your browser. Maybe this should be made more clear by making the background of the skin a random color.

**Comment by K0-RR** [comment]
Didn't work on another machine using the same browser - Brave, but worked fine when I used Vivaldi.

**Comment by evan-goode** [comment]
Strange, I couldn't reproduce on Brave either. Anyway, glad you got it working.
