### ISSUE TITLE
Lightweighter front background should be ;)

### ISSUE THREAD

**Issue by dd84ai** [unmojang/drasl#101]
![Screenshot_20240817_235942](https://github.com/user-attachments/assets/0c3a4881-1dfe-427a-961e-04f0ef7c85c1)
i have I5-10400 CPU with integrated graphics running Kubuntu 22.04 LTS.
Opening even single instance of a drasl web site (self hosted or demo) consumes all my CPU to maximum and has very low frame rate (smth like 1 frame rate per sec)
It really should be changed to something more lightweight.

I suspect you currently abuse  some heavy videographics to see it rapid

![Screenshot_20240818_022058](https://github.com/user-attachments/assets/100552a1-9c96-4057-8f82-e3d448b18d9a)
screenshot of chrome performance measure confirms the load beiing in GPU ;)

Looks like framerate for this painting around 182ms per frame
![Screenshot_20240818_022207](https://github.com/user-attachments/assets/74cda730-391e-4c51-bbd7-0ad69d0cf513)

P.S. clarification, my CPU with integrated graphics is enough to run at 100-200 FPS+ minecraft game with 50+ mods fine ;) Yet it is not enough to run Drasl web site except in super slow way.

**Comment by Midou36O** [comment]
It's rendering a full GPU bg using opengl, you can disable JS if you want to disable the heavy graphics

**Comment by evan-goode** [comment]
Thanks for filing this, I agree that the background should perform better or be swapped out for something simpler. I think a few tweaks to the shader could make it a lot faster; I didn't spend much time optimizing it so there's bound to be some low-hanging fruit. In the meantime you can disable it with `EnableBackgroundEffect = false` in `config.toml`.

**Comment by dd84ai** [comment]
> In the meantime you can disable it with `EnableBackgroundEffect = false` in `config.toml`.

Thanks. that helped ;)

**Comment by evan-goode** [comment]
I pushed a commit to https://github.com/evan-goode/drasl/tree/evan-goode/optimize-background that should speed up the background quite a bit on low-end systems.

Things I did in that commit:
- Remove an array access (well, 16 array accesses per texel per frame)
- Reduce number of texture lookups from 16 to 5

Things I tried that seemed to have no effect:
- Any changes to the vertex shader
- Simplifying the geometry of the torus
- Optimizing the math in `end_portal_layer`
- Reducing the size of the texture from 256x256 to 128x128

The expensive part seems to be the multiple `textureProj` calls in the fragment shader that are dependent on `u_time`---these are referred to as "dynamic texture lookups". According to https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html:

> Dependent texture reads are supported at no performance cost on OpenGL ES 3.0–capable hardware

but this seems to not be true here. We are using `glslVersion: THREE.GLSL3`, so the shader is being compiled as an OpenGL ES 3.0 shader, and three.js will use WebGL 2 if available.

What I would try next is moving the texture coordinate calculations to the vertex shader and passing them as `varying` to the fragment shader. I think I need to look into "multitexturing"?

Testing this on an i5-4300U at 2560x1440, this patch already improves the performance from 12 FPS to 55-60 FPS.

HOWEVER...

>  Opening even single instance of a drasl web site (self hosted or demo) consumes all my CPU to maximum and has very low frame rate (smth like 1 frame rate per sec)
> I5-10400 CPU
> P.S. clarification, my CPU with integrated graphics is enough to run at 100-200 FPS+ minecraft game with 50+ mods fine ;) Yet it is not enough to run Drasl web site except in super slow way.

This shader should have identical performance characteristics to the shader used by Minecraft since their implementations are so similar. At 1 FPS, it sounds like what is happening is a browser bug or configuration problem causing Chromium to fall back to a WebGL software renderer. I suspect that if you try some of the examples at https://webglsamples.org/ you will get similarly poor performance. And if you go to http://mapbox.github.io/mapbox-gl-supported, you will see "supported with a major performance caveat". And if you launch Chromium from the command line you may see logs along the lines of `eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED`. I'm seeing the same failures on my Fedora system, and I'll let you know if I find a fix.

If I was correct about that, can you try viewing Drasl and some other WebGL content in Firefox and see if performance is any better there? On my broken Fedora system I get 144fps at 2560x1440 on an i7-1185G7 iGPU on Firefox, but 1 FPS on Chromium.

Luckily, Drasl could detect the software-rendering fallback using https://github.com/mapbox/mapbox-gl-supported and disable the animation if there is a "major performance caveat".

**Comment by dd84ai** [comment]
Stilll seeing at https://drasl.unmojang.org/ 1-5 frames per sec. currently 210ms per frame. (i think it was 180ms)
(i use Chrome 119.0.6045.199 here)

Fascinating. Opened from Firefox. 129.0.2, Lovely smooth performance (Smth like 60 normap fos). (same Kubuntu 22.04)

I tried opening https://webglsamples.org/blob/blob.html , this one shows 60 fps at chrome
https://webglsamples.org/aquarium/aquarium.html this one shows 11 fps at chrome (same shows 60 fps at firefox)

CPU: Intel i5-10400 (12) @ 4.300GHz 
GPU: Intel CometLake-S GT2 [UHD Graphics 630]

I see that for some reason UHD graphics 630 on Kubuntu 22.04 do not play well with Chrome 119 for this feature.

> https://mapbox.github.io/mapbox-gl-supported/
Here yes i see "Mapbox GL JS is supported with a major performance caveat (undefined)" with chrome
And it is supported with Firefox.

hmmm... for https://github.com/evan-goode/drasl/tree/evan-goode/optimize-background to try
Could u publish docker image under some tag? :)

**Comment by evan-goode** [comment]
I've merged those performance tweaks in https://github.com/unmojang/drasl/pull/105 and added a check to disable the animation if the browser is using software rendering (it will still render a still background, it just won't animate it over time). I released v2.0.2, the Docker builds should be finished shortly.
