### ISSUE TITLE
Thank you for making these possible

### ISSUE THREAD

**Issue by wizhel** [unmojang/drasl#33]
Thank you!!!!!!!!!!
I want to say more but english is not my main lang,
i really appreciate your work!!!!!!!!!!

**Comment by evan-goode** [comment]
You're welcome! Translation to other languages via community effort is something I would love to do at some point, but I don't have much experience setting that up.

Perhaps a good first step would be to translate the documentation to some other common languages, at least to Russian and Chinese since those languages  are widely spoken in this community.
