### ISSUE TITLE
HD capes not uploading, despite being possible 

### ISSUE THREAD

**Issue by catfromplan9** [unmojang/drasl#5]

**Comment by evan-goode** [comment]
I'm able to upload a 128x64 cape using the web interface, are you doing it that way or using a launcher?

Could you provide the cape file that doesn't work?

**Comment by catfromplan9** [comment]
> I'm able to upload a 128x64 cape using the web interface, are you doing it that way or using a launcher?
> 
> Could you provide the cape file that doesn't work?

Website, yes. I am using very high res capes. Here is one

**Comment by catfromplan9** [comment]
Bump

**Comment by evan-goode** [comment]
Ok, it was checking that the width of the cape was either 64, 128, 256, or 512 when high resolution skins were allowed, but yes it's a bit dumb to hardcode an upper limit there. Now, the setting is called `SkinSizeLimit` instead of `AllowHighResolutionSkins` and the admin can pick their own upper limit, or set it to zero and have no limit. I'm currently working on configurable limits on request body size for the whole application so someone can't just upload a 4TiB skin.

Having non power-of-two sized textures seems strange to me, but other than it being square, I have no idea what MCCustomSkinLoader or other HD skin mods consider a valid skin (or cape). Looks like Blessing Skin enforces that the width must be divisible by 32: 
https://github.com/bs-community/blessing-skin-server/blob/f436c056e08df859ae15d9558ee2ec01c251aa1c/resources/lang/en/skinlib.yml#L15
I think we'll be fine to skip that check, if the skin doesn't work with some mod, that's kinda the mod's and the user's problem to worry about.

**Comment by catfromplan9** [comment]
Excellent
